config/routes.rb
Rails.application.routes.draw do
  get 'paystack/callback'
  get 'paystack/webhook'
  devise_for :users
  root to: "stokvels#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "stokvel/:stokvel_id/payout", to: "payouts#create", as: :create_payout
  post "stokvel/:id/create-members", to: "members#create_members", as: :create_members

  resources :stokvels, except: [:edit, :update] do
    resources :members, only: [:index, :new, :show, :create, :destroy]
    resources :messages, only: %i[index create]
    resources :transactions, only: %i[new create show]
    resources :users, only: %i[index]
    resources :contributions, only: [:index, :show, :new, :create]
    resources :payouts, only: [:index, :show, :new, :create]
  end
  resources :members, only: %i[update]

  resources :transactions, only: [:index] do
    member do
      get 'show_contribution'
      get 'show_payout'
    end
  end

  post "stokvels/:id/accept_invite", to: "stokvels#accept_invite", as: :accept_invite
  post "stokvels/:id/decline_invite", to: "members#declined", as: :decline_invite

  post '/paystack/callback', to: 'paystack#callback'
  post '/paystack/webhook', to: 'paystack#webhook'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 text-white" role="alert">
    <%= notice %>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 text-white" role="alert">
    <%= alert %>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

<!--    </button>
  </div>
<%# end %>-->
<!---->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light fixed-bottom">
  <div class="container">
    <ul class="navbar-nav w-100 justify-content-around">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path %>">
          <i class="fas fa-home"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= transactions_path %>">
          <i class="fas fa-wallet"></i>
        </a>
      </li>
      <li class="nav-item">
        <% if @stokvel && @stokvel.persisted? %>
          <a class="nav-link" href="<%= stokvel_path(@stokvel) %>">
            <i class="fas fa-users"></i>
          </a>
        <% else %>
          <span class="nav-link disabled">
            <i class="fas fa-users"></i>
          </span>
        <% end %>
      </li>
      <% if @stokvel.present? && @stokvel.persisted? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= stokvel_members_path(@stokvel) %>">
            <i class="fas fa-list"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= stokvel_messages_path(@stokvel) %>">
            <i class="fas fa-comments"></i>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>