config/routes.rb
Rails.application.routes.draw do
  get 'paystack/callback'
  get 'paystack/webhook'
  devise_for :users
  root to: "stokvels#index"
  get "up" => "rails/health#show", as: :rails_health_check

  post "stokvel/:stokvel_id/payout", to: "payouts#create", as: :create_payout
  post "stokvel/:id/create-members", to: "members#create_members", as: :create_members

  resources :stokvels, except: [:edit, :update] do
    resources :members, only: [:index, :new, :show, :create, :destroy]
    resources :messages, only: %i[index create]
    resources :transactions, only: %i[new create show]
    resources :users, only: %i[index]
    resources :contributions, only: [:index, :show, :new, :create]
    resources :payouts, only: [:index, :show, :new, :create]
  end
  resources :members, only: %i[update]

  resources :transactions, only: [:index] do
    member do
      get 'show_contribution'
      get 'show_payout'
    end
  end

  post "stokvels/:id/accept_invite", to: "stokvels#accept_invite", as: :accept_invite
  post "stokvels/:id/decline_invite", to: "members#declined", as: :decline_invite

  post '/paystack/callback', to: 'paystack#callback'
  post '/paystack/webhook', to: 'paystack#webhook'
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :stokvel
  belongs_to :user
  has_many :contributions, through: :stokvel
  has_many :payouts, through: :stokvel
  has_many :transactions, dependent: :destroy
  # has_many :messages, dependent: :destroy

  enum status: { pending: 0, accepted: 1, declined: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :owned_stokvels, class_name: 'Stokvel'
  has_many :members, dependent: :destroy
  has_many :stokvels, through: :members
  has_many :messages
  has_many :contributions, dependent: :destroy
  has_many :payouts, dependent: :destroy
  
  # has_one_attached :photo
  validates :balance, numericality: {greater_than_or_equal_to: 0 }
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stokvel
  before_action :set_member, only: [:destroy]
  def index
    # Check if the request came from the stokvel show page
    if request.referer != stokvel_url(@stokvel)
      redirect_to stokvel_url(@stokvel), alert: "You can only view members from the stokvel show page."
    else
      # Retrieves members specific to the Stokvel group being viewed
      @members = @stokvel.members.includes(:contributions).order('contributions.created_at DESC')

      # Fetch the last contribution date and amount for each member
      @last_contributions = {}
      @members.each do |member|
        last_contribution = member.contributions.last
        @last_contributions[member.id] = last_contribution ? { date: last_contribution.created_at.to_date, contribution_amount: last_contribution.contribution_amount } : nil
      end
    end
  end

  # show details of a  member of a specific stokvel group
  def show
    @stokvel = Stokvel.find(params[:stokvel_id])
    @member = @stokvel.members.find(params[:id])
    @users_not_in_stokvel = User.where.not(id: @stokvel.members.pluck(:user_id))  # Get users not in the stokvel
  end

  def new
    @stokvel = Stokvel.find(params[:stokvel_id])
    @users_not_in_stokvel = User.where.not(id: @stokvel.members.pluck(:user_id))
  end

  def create
    @stokvel = Stokvel.find(params[:stokvel_id])
    @member = @stokvel.members.new(member_params)
    @member.user = current_user
    if @member.save
      redirect_to @stokvel, notice: "Member was successfully added."
    else
      render :new
    end
  end

  def create_members
    @user_ids = params[:member_ids]
    @stokvel = Stokvel.find(params[:id])
    @user_ids.each do |user_id|
      member = Member.new(user_id: user_id,
                          stokvel_id: @stokvel.id,
                          status: "pending",
                          balance: 0,
                          join_date: Date.today)
    member.save
    end
    redirect_to stokvel_path(params[:id]), notice: "Members were successfully added."
    # redirect_to stokvel_path(params[:stokvel_id]), notice: "Members were successfully added."
  end

  def accepted
    member = Member.find_by(stokvel_id: params[:stokvel_id], user_id: params[:user_id])
    if member
      member.update(status: "accepted")
      redirect_to stokvel_path(params[:stokvel_id]), notice: "Member accepted ."
    else
      redirect_to stokvel_path(params[:stokvel_id]), notice: "Member not found."
    end
  end

  def declined
    member = Member.find_by(user_id: current_user, stokvel_id: params[:id])
    if member
      member.update(status: "declined")
      redirect_to root_path, notice: "User has declined invitation."
    else
      redirect_to root_path, notice: "Member not found."
    end
  end

  def update
    @member = current_user.member.find_by(stokvel_id: params[:stokvel_id])
    if params[:commit] == 'Accept'
      @member.update(status: 'accepted')
      redirect_to stokvel_path(@member.stokvel_id), notice: 'Invitation accepted successfully.'
    elsif params[:commit] == 'Decline'
      @member.update(status: 'declined')
      if @member.update.stokvel.status == 'declined'
        @member.destroy
        redirect_to stokvel_path(@member.stokvel_id), notice: 'Invitation declined and deleted.'
      else
      redirect_to stokvel_path(@member.stokvel_id), notice: 'Invitation declined successfully.'
      end
    end
  end

  def destroy
    @stokvel = Stokvel.find(params[:stokvel_id])
    @member = @stokvel.members.find(params[:id])

    if @member.destroy
      respond_to do |format|
        format.html { redirect_to stokvel_path(@stokvel), notice: 'Member was successfully deleted.' }
        format.js   # This will look for a destroy.js.erb file
      end
    else
      respond_to do |format|
        format.html { redirect_to stokvel_path(@stokvel), alert: 'Failed to delete member.' }
        format.js   # This will look for a destroy.js.erb file
      end
    end
  end

  # def destroy
  #   @member.destroy
  #   redirect_to stokvel_members_path(@stokvel), notice: 'Member was successfully removed.'
  # end

  private
  def set_stokvel
    @stokvel = Stokvel.find_by(id: params[:stokvel_id]) # Use find_by to avoid exceptions
    unless @stokvel
      redirect_to stokvels_path, alert: "Stokvel not found." # Redirect if not found
    end
  end

  def set_member
    @member = @stokvel.members.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:user_id)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<br>
<div class="container">
<br>
  <div id="page_main">
    <div class="form-group">
    <%= f.label :user_id, "Invite New Member:" %>
    <%= f.collection_select :user_id, User.all, :id, ->(user) { "#{user.first_name} #{user.last_name}" }, prompt: "Select user" %>
  </div>
  <%= f.submit "Invite", class: "btn btn-primary" %>
  </div>
</div>

app/views/members/_users_list.html.erb
<style>
  .add-members-list-container {
      background-color: #242C3B; /* Match the container background */
      padding: 20px;
      border-radius: 10px;
      margin: 20px auto;
      max-width: 900px;
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
  }

  .user-list-card {
      background-color: #fff; /* White background for user cards */
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 10px;
      display: flex;
      justify-content: space-between;
      align-items: center;
  }

  .members-body {
      display: flex;
      justify-content: space-between; /* Space between elements */
      align-items: center; /* Center items vertically */
  }

  .checkbox-container {
      display: flex;
      align-items: center; /* Center checkbox and label vertically */
  }

  .checkbox-container input[type="checkbox"] {
      margin-left: 10px; /* Space between checkbox and label */
  }

  .member-details {
      display: flex;
      align-items: center;
  }

  .members-user-text {
      margin-left: 10px; /* Space between avatar and text */
  }

  .hide-checkbox {
      display: none; /* Hide the default checkbox */
  }

  .next-button {
      margin-top: 20px; /* Space above the button */
  }

  .white-text {
      color: #fff; /* White text for the button */

      .form-group {
      display: flex;
      align-items: center;
  }

  .form-group input[type="checkbox"] {
      display: none; /* Hide the default checkbox */
  }

  .form-group label {
      cursor: pointer; /* Change cursor to pointer */
      padding: 5px;
      border: 1px solid #ccc; /* Add border to label */
      border-radius: 5px; /* Rounded corners */
      background-color: #f0f0f0; /* Light background */
  }

  .form-group input[type="checkbox"]:checked + label {
      background-color: #0ea5e9; /* Change background when checked */
      color: #fff; /* Change text color when checked */
  }
  }
</style>
<div class="add-members-list-container" data-search-users-target="users_list">
  <h2 class="section-title">Add Members</h2>
  <%= form_with url: create_members_path(@stokvel) do |f| %>
    <% users.each do |user| %>
      <div class="user-list-card">
        <div class="members-body">
          <div class="member-details">
            <%# if user.photo.attached? %>
            <%#= cl_image_tag user.photo.key, height: 44, width: 53, crop: :fill, class: "avatar" %>
            <%# else %>
            <%#= image_tag "placeholder.png", class: "styled-image" %>
            <%# end %>
            <div class="members-user-text">
              <h5><%= user.first_name %> <%= user.last_name %></h5>
              <p><%= user.email %></p>
            </div>
          </div>
          <div class="form-group">
            <div class="checkbox-container">
              <%= f.check_box :member_ids, {multiple: true}, user.id, nil %>
              <%= f.label "member_ids_#{user.id}", "+" %>
            </div>
          </div>
        </div>
      </div>
      <br>
    <% end %>
    <div class="next-button" style="text-align: center;">
      <p class="white-text"><%= f.submit "Add Members", class: "action-button" %></p>
    </div>
  <% end %>
</div>

app/views/members/destroy.js.erb
// Assuming you have a way to identify the member card, e.g., by a data attribute
document.querySelector(`.member_card[data-member-id="<%= @member.id %>"]`).remove();

app/views/members/index.html.erb
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOM4cAiEdF9yK4niPY+TjzSVmWAGPflkG8voMjUw" crossorigin="anonymous">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap');

    body {
      font-family: 'Montserrat', sans-serif;
      background-color: #fff;
            color: #fff;

      display: flex;
      flex-direction: column;
      min-height: 100vh;
      margin: 0;
      padding: 0;
    }

    .parent_container {
      background-color: #fff;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      background-color: #f2f2f2;
      font-family: Arial, sans-serif;
    }

    .container {
      background-color: #242C3B;
      color: #fff;
      padding: 30px;
      border-radius: 8px;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
      width: 90%;
      max-width: 800px;
    }

    .header {
      position: fixed;
      width: 100%;
      top: 0;
      left: 0;
      z-index: 100;
      background-color: #242C3B;
      padding: 10px 20px;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    h4 {
      color: #fff;
    }

    .members_container {
      display: flex;
      flex-direction: column;
      gap: 15px;
    }

    .member_card {
      display: flex;
      align-items: center;
      padding: 15px;
      border: 1px solid #ddd;
      border-radius: 5px;
      transition: background-color 0.3s;
      background-color: #fff;
    }

    .member_card:hover {
      background-color: #f9f9f9;
    }

    .member_details {
      display: flex;
      align-items: center;
      width: 100%;
    }

    .avatar {
      width: 44px;
      height: 53px;
      border-radius: 50%;
      margin-right: 15px;
      border: 2px solid #337ab7;
    }

    .member_info {
      display: flex;
      flex-direction: column;
      justify-content: center;
      flex-grow: 1;
    }

    .contribution_info {
      margin-top: 10px;
      font-size: 14px;
      color: #555;
    }

    .contribution_amount {
      font-weight: bold;
      color: #337ab7;
    }

    h4 {
      color: #333;
    }

    h5 {
      margin: 0;
      color: #337ab7;
    }

    .delete-member-button {
      background-color: transparent; /* No background */
      border: none; /* No border */
      cursor: pointer; /* Pointer cursor on hover */
      color: red; /* Text color */
      font-size: 16px; /* Font size */
      padding: 0; /* No padding */
      margin-left: 10px; /* Space between text and icon */
    }

    .delete-member-button:hover {
      opacity: 0.8; /* Slightly transparent on hover */
    }
  </style>
</head>
<body>
  <div class="parent_container">
    <br>
    <br>
    <br>
    <div class="container">
      <br>
      <br>
      <div class="back_container">
        <div class="header">
          <div class="logo">
            <%= image_tag "logo.png", alt: "Stokvel Logo" %>
          </div>
          <br>
          <br>
          <br>
          <br>
        </div>
        <br>
        <h4>Members of <%= @stokvel.name %></h4>
        <br>
        <div class="members_container">
          <% @members.each do |member| %>
            <div class="member_card" data-member-id="<%= member.id %>">
              <div class="member_details">
                <div class="member_info">
                  <h5><%= member.user.first_name %></h5>
                  <div class="contribution_info">
                    <% if @last_contributions[member.id].present? %>
                      <p>Last Contribution Date: <%= @last_contributions[member.id][:date] %></p>
                    <% end %>
                  </div>
                  <% if @stokvel.user_id == member.user.id && member.id == current_user.id %> <!-- Check if the member is the creator -->
                    <%= button_to stokvel_member_path(@stokvel, member), method: :delete, data: { confirm: 'Are you sure you want to delete this member?' }, class: 'delete-member-button', remote: true do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <br>
          <br>
          <br>
        </div>
      </div>
      <br>
      <br>
      <br>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
</body>

app/views/members/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>Add Members - Stokvest Dashboard</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap');

      body {
          font-family: 'Montserrat', sans-serif;
          background-color: #fff;
          display: flex;
          flex-direction: column;
          min-height: 100vh;
          margin: 0;
          padding: 0;
      }

      .parent_container {
          display: flex;
          flex-direction: column;
          align-items: center;
          padding: 20px;
      }

      .container {
          background-color: #242C3B;
          padding: 20px;
          border-radius: 10px;
          margin: 20px auto;
          max-width: 900px;
          box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
      }

      .back_container {
          background-color: #dedede;
          margin: 0;
          padding: 10px;
          border-radius: 10px;
      }

      .header {
          position: fixed;
          width: 100%;
          top: 0;
          left: 0;
          z-index: 100;
          background-color: #242C3B;
          padding: 10px 20px;
          display: flex;
          justify-content: center;
          align-items: center;
      }

      .greeting-section {
          color: #333;
          font-size: 36px;
      }

      .logo {
          display: flex;
          justify-content: space-between;
          font-size: 24px;
          font-weight: bold;
          background: #242C3B;
      }

      .section-title {
          color: #fff;
      }

      .section-content {
          background-color: #fff;
          padding: 15px;
          border-radius: 8px;
          margin-bottom: 20px;
      }

      .form-control {
          width: 100%;
          padding: 10px;
          margin: 5px 0;
          border-radius: 5px;
          border: 1px solid #ccc;
      }

      .action-button {
          background-color: #0ea5e9;
          color: #fff;
          padding: 10px 20px;
          border-radius: 8px;
          cursor: pointer;
          text-align: center;
          text-decoration: none;
          border: none;
          font-size: 16px;
          margin-top: 10px;
      }

      .action-button:hover {
          background-color: #0a85e9;
      }
    </style>
  </head>
  <body>
    <div class="parent_container">
      <br>
      <div class="container">
        <br>
        <div class="back_container">
          <div class="header">
            <div class="logo">
              <%= image_tag "logo.png", alt: "Stokvel Logo" %>
            </div>

          </div>
          <div class="greeting-section">
          <a href="#" onclick="history.back(); return false;">
          <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAB4AAAAeCAYAAAA7MK6iAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAZ0lEQVR4nO2WMQqAQAwE5xMR/f9LrETRxit8jsdJbKwsNIK306UaWJYlIMR9GmABeoKlCdiBMUpqwOrSDWglfRLF+ypWTXsLs0uTjwW/F9sl6k7yCEyxo8J99PpMkeJTXhZuOC5RPRnBEDtxjsnsowAAAABJRU5ErkJggg==" alt="Back" style="width: 20px; height: 20px;">
        </a>
            <h4>Add members to <strong><%= @stokvel.name %></strong></h4>
          </div>
        </div>
        <div class="section">
          <h2 class="section-title">Search for Users</h2>
          <div class="section-content" data-controller="search-users" id="search_users">
            <%= form_with url: stokvel_users_path(@stokvel), method: :get, html: {class: "mb-2", data: {search_users_target: "form"}} do |f| %>
              <%= f.text_field :query,
                                          class: "form-control search-bar",
                                          placeholder: "Search for a user...",
                                          value: params[:query],
                                          data: {
                                              search_users_target: "input",
                                              action: "keyup->search-users#update"
                                          } %>
            <% end %>
            <div data-search-users-target="results"></div>
            <%= render "users_list", users: @users_not_in_stokvel %>
          </div>
        </div>
        <!--  <script>
    document.getElementById("back_arrow").addEventListener("click", function(event) {
    event.preventDefault();
    window.location.href = "../";
    });
  </script>-->
      </div>

app/views/members/show.html.erb
<h1>Stokvel Details</h1>
<!-- Show Stokvel details -->
<%= render 'new' %>
<!-- Button to trigger the modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addMemberModal">
  Add New Member
</button>